### PR TITLE
Feature/context

### PR DESCRIPTION
**Pull request by rmichela**

### CODE REVIEW

**Comment by cbornet** [comment]
I understand that the AmbientContext is a helper to get Metadata values from endpoint methods, is that correct ?
Do you know if there's a way to add metadata values to responses ?

**Comment by rmichela** [comment]
Request trailers can contain additional Metadata, although trailer metadata isn't readily accessible from stub API. Individual response messages cannot have their own metadata.

**Comment by cbornet** [comment]
The question is: can I get metadata in a Rxgrpc stub API from the Ambient context ?

**Comment by rmichela** [comment]
I haven't tried that yet, but it _should_ work in theory. You would have to add the ambient context interceptors when using `ManagedChannelBuilder` and `ServerBuilder`. Since ambient context leverages the standard grpc `Context`, and RxGrpc correctly handles the `Context`, it should "just work".

**Comment by cbornet** [comment]
Great ! This can be very helpful !

**Pull request merged**
