### PR TITLE
Bump gson to 2.8.9

### PR DESCRIPTION
**Pull request by yeikel**
See https://github.com/google/gson/pull/1991

### CODE REVIEW

**Comment by yeikel** [comment]
image

**Comment by nikolay-pshenichny** [comment]
@yeikel , let me try to close/re-open the PR to see if we can get CLA re-evaluated.

**Comment by yeikel** [comment]
@nikolay-pshenichny Thank you for merging it

Could you please release a patch with this upgrade?

**Comment by nikolay-pshenichny** [comment]
@yeikel , https://github.com/salesforce/grpc-java-contrib/releases/tag/gson-v2.8.9
Thank you!

**Comment by yeikel** [comment]
Thank you. @nikolay-pshenichny 

I was expecting to see jprotoc 1.2.1 or similar

Are you pushing that tag to maven central?

**Comment by nikolay-pshenichny** [comment]
@rmichela , could you please help with this ^ ?

**Comment by rmichela** [comment]
Released in 1.2.1 to maven central

**Comment by yeikel** [comment]
I am guessing it takes a while to update because I can't find it in Maven Central yet
[
g:com.salesforce.servicelibs AND a:jprotoc AND v:1.2.1](https://search.maven.org/search?q=g:com.salesforce.servicelibs%20AND%20a:jprotoc%20AND%20v:1.2.1)

**Comment by yeikel** [comment]
Unfortunately it is still not showing up

**Comment by yeikel** [comment]
I can see it now. Thank you!

**Pull request merged**
