### PR TITLE
Gradle builds supported.

### PR DESCRIPTION
**Pull request by noel-yap**

### CODE REVIEW

**Comment by rmichela** [comment]
Thanks for the PR! I have a couple questions:

1. Which gradle lifecycle phases are supported, and how do they compare to maven?
2. Can the top-level .gradle files be merged into a single .gradle file?
3. How does gradle work with JProtoc plugins? Can you document JProtoc usage with gradle in `jprotoc/README.md`?

Also, when I run `./gradlew test`, I get a build failure involving unresolved symbol references in generated test classes in the `jprotoc-test` project.

**Comment by noel-yap** [comment]
Currently `gradlew build` is supported. It'll compile and run tests as well as building a self-contained, self-executing jar executable (ie the caller need not explicitly call `java` on it and can move the artifact anywhere in the file system). I'm working on implementing `publish` but need to allow setting the repository since the project isn't published to maven central yet.

I _think_ uber Gradle files can be done but it would require some work. What's the rationale for wanting this?

There's a Gradle protobuf plugin. I'm imagining, perhaps incorrectly, using JProtoc and Gradle to produce a self-contained, self-executing jar file which would be used by `protoc`. Once I have an end-to-end thing that works, I'll document the usage.

I'll see what dependencies need to be hooked up so that `gradlew test` works. I've been running `gradlew build` so I haven't run into this issue. Thanks for pointing it out.

**Comment by rmichela** [comment]
I think it's OK if gradle doesn't implement every build lifecycle step, since maven is the primary build system for this project and will (soon) publish to maven centeral. What is the final outcome you are trying to achieve with gradle? Are you only looking to make jprotoc consumable from gradle-based projects, or are you looking to implement more?

**Comment by noel-yap** [comment]
Once `jprotoc` is published to maven central, there's no need for Gradle support. The primary purpose is so that I can easily build and use it while it's not in maven central. Having said that, I now see that there's no need to merge this PR and I can keep it on an internal vendor branch.

Of course, I may run into issues for which I'll submit other PRs.

**Comment by rmichela** [comment]
Would it make sense to author a custom gradle plugin to make JProtoc plugins as easy to use in gradle as they are in Maven?

**Comment by noel-yap** [comment]
I don't know enough at this time about JProtoc use to say either way. It may turn out to be easy enough to use JProtoc with the current Gradle protobuf plugin at most with a bit extra. I'll keep this option in mind, though.

**Comment by rmichela** [comment]
Closing since no longer needed

**Pull request closed without merging**
