### PR TITLE
Fixed: FileInputStream stays open until you close the JVM process

### PR DESCRIPTION
**Pull request by kjarrio**
Fixed: FileInputStream stays open until you close the JVM process, which causes the dump file to get locked.

### CODE REVIEW

**Comment by rmichela** [comment]
Thanks for the fix! Do you need this released immediately?

**Comment by kjarrio** [comment]
No, I managed to patch it yesterday by replacing the single file. I've got some time on my hands before getting back to work, so I might as well contribute a bit more, is there anything specific you need or want for the jprotoc project? I'll make a pull request later adding a few more examples of usage to get people started as the couple of example generators in there don't go into too much detail.

**Comment by rmichela** [comment]
Additional documentation and examples would be great!

**Comment by rmichela** [comment]
Released in 1.0.0

**Pull request merged**
